apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: paas-demo-app-config
  labels:
    app: paas-demo-app
    app.kubernetes.io/name: paas-demo-app
    app.kubernetes.io/component: frontend
data:
  THREAT_LEVEL: "Green" # `GREEN`, `AMBER`, `RED`, `BLACK`
