apiVersion: v1
kind: ServiceAccount
metadata:
  name: paas-demo-pipeline
  labels:
    app: paas-demo-app
# Add image pull/push secret references here after creating them:
# secrets:
#   - name: quay-push-secret
# imagePullSecrets:
#   - name: quay-push-secret
