apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: paas-demo-app
  labels:
    app: paas-demo-app
    app.kubernetes.io/name: paas-demo-app
spec:
  type: ClusterIP
  selector:
    app: paas-demo-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
